### ISSUE TITLE
JDK 9.0.1 GA Errors

### ISSUE THREAD

**Issue by JeffGreen** [YaSuenag/jdt-2017-examples#1]
Hello!  This is a neat set of examples.  Unfortunately I can't seem to get them to run on JDK 9.0.1 GA.  In GA, it seems that "--permit-illegal-access" has changed to "--illegal-access=debug".  If I make that switch and run padd (for example), I get:

```
Exception in thread "main" java.lang.IllegalAccessError: class helper.AsmInjector (in unnamed module @0x7a46a697) cannot access class jdk.vm.ci.runtime.JVMCI (in module jdk.internal.vm.ci) because module jdk.internal.vm.ci does not export jdk.vm.ci.runtime to unnamed module @0x7a46a697
	at helper.AsmInjector.<init>(AsmInjector.java:31)
	at PAddTest.main(PAddTest.java:16)
Makefile:58: recipe for target 'padd' failed
```
Any thoughts on this?

Thanks.

**Comment by YaSuenag** [comment]
Thank you for your report!
This error is caused by Jigsaw.

I've fixed it in new commit. Could you test it?

If you use JVMCI test code from jdk10 (jdk) testcases, you need to change the C++ type in `TestHotSpotVMConfig.java`. Please see `README.md`.

**Comment by JeffGreen** [comment]
Yes, it works perfectly now using jdk9.0.1.  It seems like the difference was the "--add-opens" command line parameter.  

Thanks for posting these examples - they seem to be the only JVMCI ones on the web.  JVMCI seems very cool, particularly for enabling SIMD, but also for more complex use-cases like integrating bits of LLVM.
